channel_alias: https://artifactory.esss.lu.se/artifactory/api/conda
channels:
  - conda-forge
  - https://artifactory.esss.lu.se/artifactory/api/conda/conda-e3-virtual
dependencies:
  - stream
  - python=3.11
